on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write # यहाँ सुधार किया गया है

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v6 को v4 किया गया

      - uses: tibdex/github-app-token@v1.8.2
        if: ${{ !env.ACT }}
        id: create-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4 # v6 को v4 किया गया
        if: ${{ !env.ACT }}
        with:
          token: ${{ steps.create-app-token.outputs.token }}

      - uses: actions/setup-node@v4 # v6 को v4 किया गया
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Update internal playlists
        id: playlist-update
        run: |
          npm run playlist:update || echo "No updates"
          if [ -f temp/logs/playlist_update.log ]; then
            echo "processed_issues=$(cat temp/logs/playlist_update.log)" >> $GITHUB_OUTPUT
          else
            echo "processed_issues=0" >> $GITHUB_OUTPUT
          fi

      - name: Check internal playlists
        run: |
          npm run playlist:lint || true
          npm run playlist:validate || true

      - name: Generate public playlists
        run: npm run playlist:generate

      - name: Create .api/streams.json
        run: npm run playlist:export

      - name: Update readme
        run: npm run readme:update

      - name: Setup git
        run: |
          git config user.name "iptv-bot[bot]"
          git config user.email "84861620+iptv-bot[bot]@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git add .
          git commit --allow-empty -m "[Bot] Update playlists and streams" --no-verify
          git push origin HEAD
